### ISSUE TITLE
specto update to 2016.6.18.4 broken

### ISSUE THREAD

**Issue by kostaboxon** [mrknow/specto#1]
Version update to 2016.6.18.4 has broken the addon.
Returning errors.
I'm running Linux Jarvis 16.1 so it is not just a windows issue.

**Comment by mrknow** [comment]
Try install repository specto repository 

Here you have more information about this change http://filmkodi.com/en/themes-for-specto/

**Comment by kostaboxon** [comment]
It is okay. I have the repository. It fixed itself with update.
