### ISSUE TITLE
Quick fix for tv/movie imdb listings

### ISSUE THREAD

**Issue by mortael** [mrknow/specto#2]
Hey MrKnow,

created a quick fix for the imdb listings
[plugin.video.specto-2016.07.09.2a.zip](https://github.com/mrknow/specto/files/386089/plugin.video.specto-2016.07.09.2a.zip)

**Comment by misa2610** [comment]
Missing next page

**Comment by azrin1972** [comment]
May I know which files were edited to fix this? I can help to create a pull request for this.

**Comment by mortael** [comment]
It's been fixed in the addon for a long time now....

**Comment by azrin1972** [comment]
I'm sorry but I beg to differ - it does not work in the latest updated version that I tested this morning.

**Comment by mortael** [comment]
Ah sorry, don't use Specto myself.
I changed tvshows.py and movies.py.
