### ISSUE TITLE
Kodi 17 Is It Any Good?

### ISSUE THREAD

**Issue by BankruptEd** [mrknow/specto#20]
Not an issue. I was just wondering what people are thinking about the latest Kodi? Is it good? Better? Worse? If it's problematic, I would probably hold off upgrading. Anyone have an opinion on this? 

Are updates tailored towards 17? Do I HAVE to upgrade for future updates to work?

**Comment by azrin1972** [comment]
I've used it since beta version. No issue so far. Better interface. Faster and more responsive it seems

**Comment by BankruptEd** [comment]
Hmm, okay then, I will give er a try. Thanks for your reply Azrin.
